# Generated by Django 6.1.1 on 2026-10-06 09:05

import django.core.validators
import django.db.models.deletion
import items.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], max_length=5)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('BAGS', 'Bags'), ('BOOKS', 'Books & Stationery'), ('CLOTHING', 'Clothing'), ('WALLETS', 'Wallets, Cards & IDs'), ('KEYS', 'Keys'), ('ACCESSORIES', 'Accessories & Jewellery'), ('SPORTS', 'Sports Items'), ('OTHER', 'Other')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('LIBRARY', 'Library'), ('MAIN_BUILDING', 'Main Building'), ('CLASSROOM_BLOCK', 'Classroom Block'), ('COMPUTER_LAB', 'Computer Lab'), ('CANTEEN', 'Canteen'), ('SPORTS_GROUND', 'Sports Ground'), ('PARKING', 'Parking Area'), ('AUDITORIUM', 'Auditorium'), ('MAIN_GATE', 'Main Gate'), ('OTHER', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=items.models.item_image_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('status', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found'), ('POTENTIAL_MATCH', 'Potential Match'), ('VERIFICATION_PENDING', 'Verification Pending'), ('RECOVERED', 'Recovered'), ('CLOSED', 'Closed')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
