# Generated by Django 6.1.1 on 2026-10-08 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_score', models.FloatField()),
                ('category_score', models.FloatField()),
                ('color_score', models.FloatField()),
                ('brand_score', models.FloatField()),
                ('location_score', models.FloatField()),
                ('time_score', models.FloatField()),
                ('final_score', models.FloatField()),
                ('status', models.CharField(choices=[('VERIFICATION_PENDING', 'Verification pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='VERIFICATION_PENDING', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_found', to='items.item')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_lost', to='items.item')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ASKED', 'Waiting for answer'), ('ANSWERED', 'Answered')], default='ASKED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='matcher.match')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
