# Generated by Django 6.1.1 on 2026-10-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('VERIFICATION_PENDING', 'Verification pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn'), ('COMPLETED', 'Item recovered')], default='VERIFICATION_PENDING', max_length=25),
        ),
    ]
